"""empty message

Revision ID: 3cfde9b2fda4
Revises: e3bb246415a3
Create Date: 2024-07-10 14:12:15.399555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfde9b2fda4'
down_revision = 'e3bb246415a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add_classes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_edit_classes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete_classes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_delete_classes')
        batch_op.drop_column('can_edit_classes')
        batch_op.drop_column('can_add_classes')

    # ### end Alembic commands ###
