"""Add roll number to Student

Revision ID: bd69c0daddca
Revises: 3cfde9b2fda4
Create Date: 2024-07-14 17:06:46.325809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd69c0daddca'
down_revision = '3cfde9b2fda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['roll_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('roll_number')

    # ### end Alembic commands ###
